#!/usr/bin/env php
<?php

ini_set('display_errors', 1);
error_reporting(E_ALL);

require __DIR__ . '/vendor/autoload.php';

$server = new \Wrench\Server('ws://localhost:1103/', array(
    'allowed_origins'            => array(
        'mysite.localhost'
    ),
));

$server->registerApplication('sock/echo', new \Wrench\Application\EchoApplication());
$server->run();